---
- name: Add grafana repository
  yum_repository:
    name: grafana
    gpgcheck: yes
    gpgkey: "{{ grafana_yum_gpgkey_uri }}"
    baseurl: "{{ grafana_yum_repobase }}"
  become: true

- name: Install Grafana Release
  yum:
    name: "grafana-{{ grafana_version }}"
  become: true
  notify:
    - grafana restart
